#!/usr/bin/env python3
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / "templates"
OUT = ROOT / "frontend" / "pages"
OUT.mkdir(parents=True, exist_ok=True)

SRC_FILES = [
    "controls/linearization.html",
    "controls/spectral-decomposition.html",
    "controls/differential-equations.html",
    "controls/difference-equations.html",
    "controls/dynamical-systems.html",
    "algebra_logic/modular-powers.html",
    "algebra_logic/hasse-diagram.html",
    "algebra_logic/boolean-polynomials.html",
    "algebra_logic/chinese-remainder-theorem.html",
    "algebra_logic/bezout-identity.html",
    "linear_algebra/laplace-determinant.html",
    "linear_algebra/eigenvalues-eigenvectors.html",
    "linear_algebra/linear-systems.html",
    "operations_research/simplex.html",
    "operations_research/complementary-conditions.html",
    "analysis/function-study.html",
    "analysis/integrals.html",
]

HTML_SHELL = """<!DOCTYPE html>
<html lang=\"it\" data-page-title=\"{title}\">
<head>
  <meta charset=\"UTF-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
  <title>{title} - Matrix Tools</title>
  <link rel=\"icon\" href=\"/static/icons/favicon.ico\" sizes=\"any\" />
  <link rel=\"icon\" type=\"image/svg+xml\" href=\"/static/icons/favicon.svg\" />
  <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/static/icons/favicon-32x32.png\" />
  <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"/static/icons/favicon-16x16.png\" />
  <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/static/icons/apple-touch-icon.png\" />
  <link rel=\"manifest\" href=\"/static/icons/site.webmanifest\" />
  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />
  <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\" />
  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Manrope:wght@400;500;600;700;800&display=swap\" rel=\"stylesheet\" />
  <link rel=\"stylesheet\" href=\"https://unpkg.com/mathlive/dist/mathlive-static.css\" />
  <link href=\"/static/style.css\" rel=\"stylesheet\" />
  <link href=\"/static/panels-theme.css\" rel=\"stylesheet\" />
  {extra_styles}
</head>
<body>
  <div id=\"navbar\"></div>

  <div class=\"container-fluid\" style=\"margin-top: 100px; padding: 0rem 1.5rem 0rem 0rem !important;\">
    {content}
  </div>

  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>
  <script src=\"https://unpkg.com/mathlive@0.92.0/dist/mathlive.min.js\"></script>
  <script src=\"/static/js/layout-state.js\"></script>
  <script src=\"/static/js/site-i18n.js\"></script>
  <script src=\"/static/js/math-render-cache.js\"></script>
  <script src=\"/frontend/js/component-loader.js\"></script>
</body>
</html>
"""


def extract_block(text: str, block_name: str) -> str:
    m = re.search(r"\{%\s*block\s+" + re.escape(block_name) + r"\s*%\}(.*?)\{%\s*endblock\s*%\}", text, re.S)
    return m.group(1).strip() if m else ""


def clean_content(content: str) -> str:
    content = content.replace("{{ url_for('static', filename='js/anti-autoscroll.js') }}", "/static/js/anti-autoscroll.js")

    # For server-rendered blocks, keep only the static fallback branch.
    # Example:
    # {% if result %} ... {% else %} <empty-state> ... {% endif %}
    # becomes only <empty-state> ...
    content = re.sub(
        r"\{%\s*if\s+result\s*%\}(.*?)\{%\s*else\s*%\}(.*?)\{%\s*endif\s*%\}",
        lambda m: m.group(2),
        content,
        flags=re.S,
    )

    # Any remaining server-side `if result` blocks without else are removed.
    content = re.sub(
        r"\{%\s*if\s+result\s*%\}(.*?)\{%\s*endif\s*%\}",
        "",
        content,
        flags=re.S,
    )

    # Remove any residual Jinja directives.
    content = re.sub(r"\{%.*?%\}", "", content, flags=re.S)
    content = re.sub(r"\{\{.*?\}\}", "", content, flags=re.S)

    # Remove empty error alerts generated by stripped server placeholders.
    content = re.sub(
        r"<div class=\"alert alert-danger\">\s*<i[^>]*></i>\s*<strong>Errore:</strong>\s*</div>",
        "",
        content,
        flags=re.S,
    )

    return content


def extract_title(topbar: str) -> str:
    h2 = re.search(r"<h2[^>]*>(.*?)</h2>", topbar, re.S)
    raw = h2.group(1) if h2 else topbar
    txt = re.sub(r"<[^>]+>", "", raw)
    txt = re.sub(r"\s+", " ", txt).strip()
    return txt or "Matrix Tools"


for rel in SRC_FILES:
    src = TEMPLATES / rel
    text = src.read_text(encoding="utf-8")

    topbar = extract_block(text, "topbar_title")
    styles = extract_block(text, "styles")
    content = extract_block(text, "algorithm_content")

    title = extract_title(topbar)
    cleaned = clean_content(content)

    out_html = HTML_SHELL.format(
        title=title,
        extra_styles=styles,
        content=cleaned,
    )

    out = OUT / Path(rel).name
    out.write_text(out_html, encoding="utf-8")

print(f"Generated {len(SRC_FILES)} static pages in {OUT}")
